# Generated by Django 6.0.1 on 2026-01-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avtosalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("brand", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
